# Cloud Computing Final: Zillow Data Visualization

## Imports

In [21]:
import pandas as pd
import numpy as np
import cufflinks as cf
import chart_studio.plotly as py
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
cf.go_offline()

import datetime #to parse dates
from  geopy.geocoders import Nominatim
import kaleido
import pathlib

## Extract

**import data into pandas dataframe** </br>
The data from *Zillow* is stored on github as a *.csv* file it is then imported by URL into *pandas*

In [2]:
url = 'https://raw.githubusercontent.com/erobin27/ZillowDashboard/master/rawdata/ListAndSalePrice.csv'
df = pd.read_csv(url,index_col=0)
df.head()

df_noNaN = df.fillna(0)
df_noNaN

,SizeRank,RegionName,RegionType,StateName,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,...,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31
RegionID,,,,,,,,,,,,,,,,,,,,,
102001,0,United States,Country,0,271600.0,272967.0,279333.0,288667.0,295633.0,299267.0,...,333533.0,333850.0,340362.0,353728.0,367045.0,378267.0,381567.0,379933.0,376633.0,375000.0
394913,1,"New York, NY",Msa,NY,517967.0,523000.0,534333.0,544667.0,554666.0,560000.0,...,661666.0,668000.0,673000.0,675000.0,675000.0,666667.0,658000.0,643200.0,636533.0,631867.0
753899,2,"Los Angeles-Long Beach-Anaheim, CA",Msa,CA,798333.0,802667.0,818000.0,835000.0,848300.0,849633.0,...,996997.0,998698.0,1005698.0,1006364.0,1006666.0,999666.0,991333.0,971333.0,946667.0,931633.0
394463,3,"Chicago, IL",Msa,IL,301000.0,305967.0,319300.0,335967.0,345967.0,347967.0,...,331333.0,331667.0,338300.0,346633.0,352967.0,354667.0,354633.0,348267.0,339933.0,332967.0
394514,4,"Dallas-Fort Worth, TX",Msa,TX,341996.0,345330.0,351663.0,359830.0,366163.0,366067.0,...,350726.0,352141.0,357025.0,365358.0,374884.0,383333.0,390167.0,393500.0,396500.0,397667.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394528,90,"Daytona Beach, FL",Msa,FL,269600.0,270300.0,271833.0,274833.0,279667.0,284500.0,...,293410.0,297110.0,303500.0,314467.0,324467.0,336078.0,341612.0,346278.0,348000.0,352967.0
394531,91,"Des Moines, IA",Msa,IA,281600.0,285967.0,292293.0,297293.0,299593.0,299900.0,...,273633.0,277767.0,283300.0,291378.0,301725.0,311707.0,319628.0,320032.0,317550.0,314217.0
395006,100,"Provo, UT",Msa,UT,389707.0,397680.0,408503.0,413706.0,409865.0,402848.0,...,511346.0,515076.0,510630.0,512444.0,520778.0,537478.0,546633.0,549967.0,548467.0,545533.0
394549,104,"Durham, NC",Msa,NC,362699.0,367241.0,375112.0,382984.0,386785.0,384029.0,...,427593.0,431818.0,442273.0,466005.0,485372.0,495967.0,487633.0,480160.0,476526.0,478160.0
394602,159,"Fort Collins, CO",Msa,CO,442736.0,445785.0,448272.0,450000.0,454094.0,458112.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

#### List Of Dates: datelist

In [3]:
#List of all dates
datelist = []

for col in df.columns:
    try:
        datetime.datetime.strptime(col, '%Y-%m-%d')
        datelist.append(col)
    except:
        pass
    
datelist

['2018-01-31',
 '2018-02-28',
 '2018-03-31',
 '2018-04-30',
 '2018-05-31',
 '2018-06-30',
 '2018-07-31',
 '2018-08-31',
 '2018-09-30',
 '2018-10-31',
 '2018-11-30',
 '2018-12-31',
 '2019-01-31',
 '2019-02-28',
 '2019-03-31',
 '2019-04-30',
 '2019-05-31',
 '2019-06-30',
 '2019-07-31',
 '2019-08-31',
 '2019-09-30',
 '2019-10-31',
 '2019-11-30',
 '2019-12-31',
 '2020-01-31',
 '2020-02-29',
 '2020-03-31',
 '2020-04-30',
 '2020-05-31',
 '2020-06-30',
 '2020-07-31',
 '2020-08-31',
 '2020-09-30',
 '2020-10-31',
 '2020-11-30',
 '2020-12-31',
 '2021-01-31',
 '2021-02-28',
 '2021-03-31',
 '2021-04-30',
 '2021-05-31',
 '2021-06-30',
 '2021-07-31',
 '2021-08-31',
 '2021-09-30',
 '2021-10-31']

#### List of States: statelist

In [4]:
#List of all states
statelist = df['StateName'].unique()
statelist

array([nan, 'NY', 'CA', 'IL', 'TX', 'PA', 'DC', 'FL', 'GA', 'MA', 'MI',
       'AZ', 'WA', 'MN', 'MO', 'MD', 'CO', 'OR', 'NC', 'OH', 'NV', 'IN',
       'VA', 'TN', 'RI', 'WI', 'OK', 'KY', 'CT', 'LA', 'AL', 'UT', 'HI',
       'NM', 'NE', 'SC', 'AR', 'KS', 'ID', 'IA'], dtype=object)

#### List of Regions: regionList

In [5]:
#List of all states
regionList = df['RegionName'].unique()
regionList

array(['United States', 'New York, NY',
       'Los Angeles-Long Beach-Anaheim, CA', 'Chicago, IL',
       'Dallas-Fort Worth, TX', 'Philadelphia, PA', 'Houston, TX',
       'Washington, DC', 'Miami-Fort Lauderdale, FL', 'Atlanta, GA',
       'Boston, MA', 'San Francisco, CA', 'Detroit, MI', 'Riverside, CA',
       'Phoenix, AZ', 'Seattle, WA', 'Minneapolis-St Paul, MN',
       'San Diego, CA', 'St. Louis, MO', 'Tampa, FL', 'Baltimore, MD',
       'Denver, CO', 'Pittsburgh, PA', 'Portland, OR', 'Charlotte, NC',
       'Sacramento, CA', 'San Antonio, TX', 'Orlando, FL',
       'Cincinnati, OH', 'Cleveland, OH', 'Kansas City, MO',
       'Las Vegas, NV', 'Columbus, OH', 'Indianapolis, IN',
       'San Jose, CA', 'Austin, TX', 'Virginia Beach, VA',
       'Nashville, TN', 'Providence, RI', 'Milwaukee, WI',
       'Jacksonville, FL', 'Memphis, TN', 'Oklahoma City, OK',
       'Louisville-Jefferson County, KY', 'Hartford, CT', 'Richmond, VA',
       'New Orleans, LA', 'Buffalo, NY', 'Raleigh, NC', 'Birmingham, AL',
       'Salt Lake City, UT', 'Rochester, NY', 'Grand Rapids, MI',
       'Tucson, AZ', 'Urban Honolulu, HI', 'Tulsa, OK', 'Fresno, CA',
       'Worcester, MA', 'Stamford, CT', 'Albuquerque, NM', 'Albany, NY',
       'Omaha, NE', 'New Haven, CT', 'Bakersfield, CA', 'Knoxville, TN',
       'Greenville, SC', 'Ventura, CA', 'Allentown, PA', 'El Paso, TX',
       'Baton Rouge, LA', 'Dayton, OH', 'McAllen, TX', 'Columbia, SC',
       'Greensboro, NC', 'Akron, OH', 'North Port-Sarasota-Bradenton, FL',
       'Little Rock, AR', 'Stockton, CA', 'Charleston, SC',
       'Syracuse, NY', 'Colorado Springs, CO', 'Winston-Salem, NC',
       'Wichita, KS', 'Springfield, MA', 'Fort Myers, FL',
       'Boise City, ID', 'Toledo, OH', 'Madison, WI', 'Lakeland, FL',
       'Ogden, UT', 'Daytona Beach, FL', 'Des Moines, IA', 'Provo, UT',
       'Durham, NC', 'Fort Collins, CO'], dtype=object)

## User Setup

**User Date Selection**

In [7]:
ReportDate = '2018-08-31'

print('Dates to select from: ')
datelist

Dates to select from:

['2018-01-31',
 '2018-02-28',
 '2018-03-31',
 '2018-04-30',
 '2018-05-31',
 '2018-06-30',
 '2018-07-31',
 '2018-08-31',
 '2018-09-30',
 '2018-10-31',
 '2018-11-30',
 '2018-12-31',
 '2019-01-31',
 '2019-02-28',
 '2019-03-31',
 '2019-04-30',
 '2019-05-31',
 '2019-06-30',
 '2019-07-31',
 '2019-08-31',
 '2019-09-30',
 '2019-10-31',
 '2019-11-30',
 '2019-12-31',
 '2020-01-31',
 '2020-02-29',
 '2020-03-31',
 '2020-04-30',
 '2020-05-31',
 '2020-06-30',
 '2020-07-31',
 '2020-08-31',
 '2020-09-30',
 '2020-10-31',
 '2020-11-30',
 '2020-12-31',
 '2021-01-31',
 '2021-02-28',
 '2021-03-31',
 '2021-04-30',
 '2021-05-31',
 '2021-06-30',
 '2021-07-31',
 '2021-08-31',
 '2021-09-30',
 '2021-10-31']

In [26]:
ReportRegion = 'Raleigh, NC'

ReportPath = str(pathlib.Path().resolve())
ReportState = ReportRegion.split(',')[-1].strip()
print('Regions to select from: ')
regionList

Regions to select from:

array(['United States', 'New York, NY',
       'Los Angeles-Long Beach-Anaheim, CA', 'Chicago, IL',
       'Dallas-Fort Worth, TX', 'Philadelphia, PA', 'Houston, TX',
       'Washington, DC', 'Miami-Fort Lauderdale, FL', 'Atlanta, GA',
       'Boston, MA', 'San Francisco, CA', 'Detroit, MI', 'Riverside, CA',
       'Phoenix, AZ', 'Seattle, WA', 'Minneapolis-St Paul, MN',
       'San Diego, CA', 'St. Louis, MO', 'Tampa, FL', 'Baltimore, MD',
       'Denver, CO', 'Pittsburgh, PA', 'Portland, OR', 'Charlotte, NC',
       'Sacramento, CA', 'San Antonio, TX', 'Orlando, FL',
       'Cincinnati, OH', 'Cleveland, OH', 'Kansas City, MO',
       'Las Vegas, NV', 'Columbus, OH', 'Indianapolis, IN',
       'San Jose, CA', 'Austin, TX', 'Virginia Beach, VA',
       'Nashville, TN', 'Providence, RI', 'Milwaukee, WI',
       'Jacksonville, FL', 'Memphis, TN', 'Oklahoma City, OK',
       'Louisville-Jefferson County, KY', 'Hartford, CT', 'Richmond, VA',
       'New Orleans, LA', 'Buffalo, NY', 'Raleigh, NC', 'Birmingham, AL',
       'Salt Lake City, UT', 'Rochester, NY', 'Grand Rapids, MI',
       'Tucson, AZ', 'Urban Honolulu, HI', 'Tulsa, OK', 'Fresno, CA',
       'Worcester, MA', 'Stamford, CT', 'Albuquerque, NM', 'Albany, NY',
       'Omaha, NE', 'New Haven, CT', 'Bakersfield, CA', 'Knoxville, TN',
       'Greenville, SC', 'Ventura, CA', 'Allentown, PA', 'El Paso, TX',
       'Baton Rouge, LA', 'Dayton, OH', 'McAllen, TX', 'Columbia, SC',
       'Greensboro, NC', 'Akron, OH', 'North Port-Sarasota-Bradenton, FL',
       'Little Rock, AR', 'Stockton, CA', 'Charleston, SC',
       'Syracuse, NY', 'Colorado Springs, CO', 'Winston-Salem, NC',
       'Wichita, KS', 'Springfield, MA', 'Fort Myers, FL',
       'Boise City, ID', 'Toledo, OH', 'Madison, WI', 'Lakeland, FL',
       'Ogden, UT', 'Daytona Beach, FL', 'Des Moines, IA', 'Provo, UT',
       'Durham, NC', 'Fort Collins, CO'], dtype=object)

## Transform

#### States by Date:    df_StateByDate

In [9]:
newCols = df.StateName.tolist()
newCols.insert(0, 'Dates')

df_StateByDate = pd.DataFrame()
df_StateByDate['Dates'] = datelist

for index, row in df.iterrows():
    temp = []
    RegionName = row['RegionName']
    for date in datelist:
        temp.append(row[date])

    df_StateByDate[RegionName] = temp

df_StateByDate.fillna(0, inplace=True)
df_StateByDate

,Dates,United States,"New York, NY","Los Angeles-Long Beach-Anaheim, CA","Chicago, IL","Dallas-Fort Worth, TX","Philadelphia, PA","Houston, TX","Washington, DC","Miami-Fort Lauderdale, FL",...,"Boise City, ID","Toledo, OH","Madison, WI","Lakeland, FL","Ogden, UT","Daytona Beach, FL","Des Moines, IA","Provo, UT","Durham, NC","Fort Collins, CO"
0,2018-01-31,271600.0,517967.0,798333.0,301000.0,341996.0,252633.0,316452.0,431504.0,395000.0,...,326267.0,126933.0,293233.0,230099.0,341743.0,269600.0,281600.0,389707.0,362699.0,442736.0
1,2018-02-28,272967.0,523000.0,802667.0,305967.0,345330.0,249633.0,318765.0,431174.0,395000.0,...,342933.0,125933.0,300233.0,230478.0,350426.0,270300.0,285967.0,397680.0,367241.0,445785.0
2,2018-03-31,279333.0,534333.0,818000.0,319300.0,351663.0,253667.0,322117.0,441494.0,396333.0,...,348263.0,130383.0,308600.0,232149.0,364374.0,271833.0,292293.0,408503.0,375112.0,448272.0
3,2018-04-30,288667.0,544667.0,835000.0,335967.0,359830.0,260633.0,326872.0,452650.0,397833.0,...,354630.0,137050.0,315267.0,235594.0,377626.0,274833.0,297293.0,413706.0,382984.0,450000.0
4,2018-05-31,295633.0,554666.0,848300.0,345967.0,366163.0,269800.0,330455.0,464650.0,399467.0,...,356630.0,144717.0,317967.0,237317.0,384565.0,279667.0,299593.0,409865.0,386785.0,454094.0
5,2018-06-30,299267.0,560000.0,849633.0,347967.0,366067.0,275800.0,331804.0,474667.0,399800.0,...,361633.0,148267.0,319600.0,237748.0,387773.0,284500.0,299900.0,402848.0,384029.0,458112.0
6,2018-07-31,299900.0,560000.0,841300.0,343300.0,359533.0,279133.0,328678.0,479667.0,399933.0,...,360267.0,149900.0,319600.0,237748.0,388436.0,287833.0,299900.0,399210.0,379488.0,456446.0
7,2018-08-31,299600.0,554833.0,824233.0,336500.0,351197.0,278267.0,323792.0,476333.0,399633.0,...,354963.0,147900.0,316567.0,237713.0,385018.0,287300.0,297567.0,398379.0,371146.0,452666.0
8,2018-09-30,299267.0,549833.0,801233.0,329833.0,344597.0,275933.0,317565.0,466663.0,399300.0,...,351627.0,145767.0,311567.0,236301.0,380032.0,284267.0,294233.0,396634.0,366332.0,445981.0
9,2018-10-31,298633.0,549833.0,784567.0,324800.0,341263.0,274087.0,314178.0,461630.0,399000.0,...,348327.0,143467.0,304933.0,234543.0,374208.0,280600.0,290900.0,393288.0,363304.0,442648.0
10,2018-11-30,297267.0,550000.0,771642.0,318300.0,339600.0,271454.0,310920.0,456597.0,398333.0,...,344997.0,142133.0,301600.0,232476.0,372465.0,277267.0,289100.0,387485.0,363001.0,439322.0
11,2018-12-31,294267.0,549667.0,761608.0,309933.0,337967.0,266421.0,309291.0,449900.0,397000.0,...,341633.0,140933.0,301600.0,232132.0,373894.0,275300.0,287400.0,384028.0,362699.0,436989.0
12,2019-01-31,291567.0,549333.0,752942.0,303267.0,335500.0,258300.0,307826.0,443233.0,395667.0,...,341297.0,139900.0,306567.0,232132.0,381148.0,274600.0,285767.0,383714.0,362396.0,435322.0
13,2019-02-28,292933.0,549333.0,749633.0,306600.0,335800.0,254267.0,309129.0,443267.0,395000.0,...,345960.0,140267.0,316567.0,232476.0,389517.0,274633.0,286267.0,387737.0,367462.0,436333.0
14,2019-03-31,297967.0,554667.0,759667.0,319633.0,340767.0,257967.0,312386.0,454967.0,396333.0,...,355660.0,147633.0,328233.0,232511.0,398235.0,276633.0,288833.0,395413.0,376818.0,439433.0
15,2019-04-30,306333.0,563333.0,776600.0,336000.0,348267.0,267633.0,317272.0,471667.0,397667.0,...,369297.0,159333.0,334900.0,233923.0,405558.0,280833.0,292167.0,400616.0,386203.0,442087.0
16,2019-05-31,314300.0,573300.0,801600.0,345667.0,354933.0,279073.0,321148.0,488065.0,399333.0,...,381300.0,174000.0,337933.0,237059.0,409045.0,285666.0,293667.0,402703.0,390522.0,445720.0
17,2019-06-30,320800.0,578267.0,821933.0,347667.0,356584.0,287707.0,322451.0,496065.0,399666.0,...,388267.0,181667.0,337633.0,239815.0,405907.0,288443.0,293800.0,402010.0,389917.0,447587.0
18,2019-07-31,322433.0,578267.0,838000.0,344333.0,354884.0,293040.0,320790.0,495732.0,402666.0,...,388300.0,183300.0,336000.0,241486.0,400292.0,287577.0,291163.0,403790.0,386889.0,446567.0
19,2019-08-31,319800.0,574633.0,846000.0,337967.0,349884.0,293467.0,317151.0,489300.0,404333.0,...,384933.0,179433.0,332967.0,240970.0,395410.0,284377.0,286630.0,406405.0,380834.0,441567.0
20,2019-09-30,315553.0,573000.0,845667.0,331300.0,344933.0,293500.0,312913.0,484633.0,404333.0,...,380210.0,172767.0,328300.0,240136.0,389133.0,280767.0,280663.0,407798.0,372387.0,436600.0
21,2019-10-31,312220.0,574333.0,845933.0,324933.0,341633.0,293800.0,310109.0,483300.0,401667.0,...,374245.0,167633.0,326600.0,238809.0,379020.0,277863.0,273300.0,405683.0,363305.0,434967.0
22,2019-11-30,307220.0,577667.0,845933.0,319405.0,339997.0,293633.0,307884.0,485000.0,400667.0,...,370611.0,163133.0,324933.0,237913.0,371837.0,276896.0,266830.0,402443.0,358763.0,435667.0
23,2019-12-31,303267.0,579000.0,848933.0,311072.0,338330.0,290300.0,305770.0,483300.0,402272.0,...,368668.0,161433.0,324900.0,237710.0,371136.0,277396.0,261830.0,401050.0,358733.0,435667.0
24,2020-01-31,299800.0,577667.0,849333.0,306105.0,335297.0,286167.0,303395.0,481633.0,402272.0,...,372548.0,159867.0,326567.0,237710.0,380377.0,278333.0,261830.0,402782.0,365545.0,439490.0
25,2020-02-29,301467.0,579333.0,865667.0,309967.0,334630.0,286133.0,302939.0,486600.0,401606.0,...,379215.0,159867.0,333233.0,239467.0,391536.0,281000.0,266000.0,409516.0,376141.0,445813.0
26,2020-03-31,306500.0,586000.0,882667.0,319967.0,336297.0,289467.0,305705.0,501600.0,401967.0,...,388074.0,161533.0,341567.0,241434.0,400257.0,283667.0,271174.0,419659.0,389796.0,456813.0
27,2020-04-30,313000.0,594000.0,886000.0,327967.0,339297.0,294633.0,308219.0,513250.0,401633.0,...,393489.0,166600.0,348233.0,242468.0,401478.0,283967.0,275174.0,424392.0,395003.0,462957.0
28,2020-05-31,320633.0,599000.0,881667.0,331333.0,343133.0,301333.0,312616.0,522950.0,401300.0,...,397122.0,178466.0,351567.0,242370.0,406046.0,282300.0,277690.0,429629.0,397092.0,465967.0
29,2020-06-30,328300.0,601667.0,891333.0,336333.0,348133.0,311333.0,317147.0,531317.0,399000.0,...,403263.0,190133.0,354600.0,242439.0,416508.0,281603.0,281412.0,435163.0,398606.0,469283.0
30,2020-07-31,335300.0,611876.0,924333.0,343300.0,354800.0,323333.0,323103.0,544333.0,399333.0,...,413260.0,200100.0,354600.0,244848.0,432235.0,284803.0,284079.0,451113.0,407174.0,473983.0
31,2020-08-31,340300.0,628543.0,955333.0,348300.0,358267.0,333000.0,327956.0,551300.0,402000.0,...,421623.0,208233.0,351300.0,247483.0,439348.0,287803.0,283862.0,466467.0,417044.0,477317.0
32,2020-09-30,342600.0,642543.0,965667.0,349967.0,359933.0,336300.0,332386.0,547967.0,405000.0,...,426623.0,208266.0,343300.0,250619.0,442801.0,290000.0,281167.0,479639.0,422493.0,473000.0
33,2020-10-31,343933.0,649333.0,971000.0,349667.0,359300.0,337933.0,336056.0,539963.0,408000.0,...,431597.0,206466.0,341533.0,252569.0,443926.0,290284.0,277000.0,485841.0,426240.0,466667.0
34,2020-11-30,342633.0,651667.0,976330.0,346000.0,356726.0,334933.0,338004.0,529997.0,407333.0,...,443567.0,193133.0,341500.0,253736.0,450081.0,291918.0,273867.0,493527.0,426505.0,463333.0
35,2020-12-31,338233.0,655333.0,989330.0,339333.0,353393.0,331600.0,336460.0,522997.0,405667.0,...,453333.0,184767.0,347400.0,255687.0,457578.0,291694.0,272133.0,501335.0,427067.0,463378.0
36,2021-01-31,333533.0,661666.0,996997.0,331333.0,350726.0,324800.0,334330.0,516000.0,402633.0,...,461697.0,178233.0,352667.0,257678.0,0.0,293410.0,273633.0,511346.0,427593.0,0.0
37,2021-02-28,333850.0,668000.0,998698.0,331667.0,352141.0,321433.0,333330.0,512667.0,400892.0,...,469730.0,183233.0,359333.0,260280.0,0.0,297110.0,277767.0,515076.0,431818.0,0.0
38,2021-03-31,340362.0,673000.0,1005698.0,338300.0,357025.0,321433.0,338630.0,510967.0,401559.0,...,483663.0,187433.0,362600.0,264907.0,0.0,303500.0,283300.0,510630.0,442273.0,0.0
39,2021-04-30,353728.0,675000.0,1006364.0,346633.0,365358.0,324933.0,346200.0,516300.0,409926.0,...,505586.0,187433.0,364100.0,274907.0,0.0,314467.0,291378.0,512444.0,466005.0,0.0
40,2021-05-31,367045.0,675000.0,1006666.0,352967.0,374884.0,329967.0,356397.0,522800.0,424833.0,...,529250.0,184133.0,367433.0,287597.0,0.0,324467.0,301725.0,520778.0,485372.0,0.0
41,2021-06-30,378267.0,666667.0,999666.0,354667.0,383333.0,334000.0,364926.0,528163.0,441025.0,...,551372.0,181600.0,370900.0,298833.0,0.0,336078.0,311707.0,537478.0,495967.0,0.0
42,2021-07-31,381567.0,658000.0,991333.0,354633.0,390167.0,332333.0,371009.0,526497.0,455692.0,...,560408.0,181600.0,372567.0,304167.0,0.0,341612.0,319628.0,546633.0,487633.0,0.0
43,2021-08-31,379933.0,643200.0,971333.0,348267.0,393500.0,328667.0,372476.0,521663.0,465525.0,...,556744.0,176567.0,369233.0,307533.0,0.0,346278.0,320032.0,549967.0,480160.0,0.0
44,2021-09-30,376633.0,636533.0,946667.0,339933.0,396500.0,324633.0,370980.0,518000.0,474000.0,...,545952.0,169900.0,364933.0,311698.0,0.0,348000.0,317550.0,548467.0,476526.0,0.0
45,2021-10-31,375000.0,631867.0,931633.0,332967.0,397667.0,324600.0,370660.0,517667.0,480931.0,...,539993.0,161600.0,363267.0,318065.0,0.0,352967.0,314217.0,545533.0,478160.0,0.0

#### Date by States:    df_DateByState

In [10]:
df_DateByState = df_StateByDate.transpose()
df_DateByState.columns = df_DateByState.iloc[0]
df_DateByState.rename({'Dates':'RegionName'}, axis='columns')
df_DateByState.drop('Dates',axis=0,inplace=True)
df_DateByState.reset_index(inplace=True)
df_DateByState.rename(columns={'index':'RegionName'}, inplace=True)
df_DateByState

Dates,RegionName,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,...,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31
0,United States,271600.0,272967.0,279333.0,288667.0,295633.0,299267.0,299900.0,299600.0,299267.0,...,333533.0,333850.0,340362.0,353728.0,367045.0,378267.0,381567.0,379933.0,376633.0,375000.0
1,"New York, NY",517967.0,523000.0,534333.0,544667.0,554666.0,560000.0,560000.0,554833.0,549833.0,...,661666.0,668000.0,673000.0,675000.0,675000.0,666667.0,658000.0,643200.0,636533.0,631867.0
2,"Los Angeles-Long Beach-Anaheim, CA",798333.0,802667.0,818000.0,835000.0,848300.0,849633.0,841300.0,824233.0,801233.0,...,996997.0,998698.0,1005698.0,1006364.0,1006666.0,999666.0,991333.0,971333.0,946667.0,931633.0
3,"Chicago, IL",301000.0,305967.0,319300.0,335967.0,345967.0,347967.0,343300.0,336500.0,329833.0,...,331333.0,331667.0,338300.0,346633.0,352967.0,354667.0,354633.0,348267.0,339933.0,332967.0
4,"Dallas-Fort Worth, TX",341996.0,345330.0,351663.0,359830.0,366163.0,366067.0,359533.0,351197.0,344597.0,...,350726.0,352141.0,357025.0,365358.0,374884.0,383333.0,390167.0,393500.0,396500.0,397667.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,"Daytona Beach, FL",269600.0,270300.0,271833.0,274833.0,279667.0,284500.0,287833.0,287300.0,284267.0,...,293410.0,297110.0,303500.0,314467.0,324467.0,336078.0,341612.0,346278.0,348000.0,352967.0
91,"Des Moines, IA",281600.0,285967.0,292293.0,297293.0,299593.0,299900.0,299900.0,297567.0,294233.0,...,273633.0,277767.0,283300.0,291378.0,301725.0,311707.0,319628.0,320032.0,317550.0,314217.0
92,"Provo, UT",389707.0,397680.0,408503.0,413706.0,409865.0,402848.0,399210.0,398379.0,396634.0,...,511346.0,515076.0,510630.0,512444.0,520778.0,537478.0,546633.0,549967.0,548467.0,545533.0
93,"Durham, NC",362699.0,367241.0,375112.0,382984.0,386785.0,384029.0,379488.0,371146.0,366332.0,...,427593.0,431818.0,442273.0,466005.0,485372.0,495967.0,487633.0,480160.0,476526.0,478160.0
94,"Fort Collins, CO",442736.0,445785.0,448272.0,450000.0,454094.0,458112.0,456446.0,452666.0,445981.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

#### Latitude Longitude: LatLon_df

In [14]:
LatLon_df = df.copy()
LatLon_df.drop('RegionType', axis=1, inplace=True)
# for date in datelist:
#     LatLon_df.drop(date, axis=1, inplace=True)

tLon = []
tLat = []
for index, row in df.iterrows():
    RegionName = row['RegionName']
    geolocator = Nominatim(user_agent="Elijah")
    try:
        location = geolocator.geocode(RegionName)
        tLon.append(location.longitude)
        tLat.append(location.latitude)
    except:
        tLon.append(0)
        tLat.append(0)

LatLon_df['Latitude'] = tLat
LatLon_df['Longitude'] = tLon

LatLon_df

,SizeRank,RegionName,StateName,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,...,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,Latitude,Longitude
RegionID,,,,,,,,,,,,,,,,,,,,,
102001,0,United States,NaN,271600.0,272967.0,279333.0,288667.0,295633.0,299267.0,299900.0,...,340362.0,353728.0,367045.0,378267.0,381567.0,379933.0,376633.0,375000.0,39.783730,-100.445882
394913,1,"New York, NY",NY,517967.0,523000.0,534333.0,544667.0,554666.0,560000.0,560000.0,...,673000.0,675000.0,675000.0,666667.0,658000.0,643200.0,636533.0,631867.0,40.712728,-74.006015
753899,2,"Los Angeles-Long Beach-Anaheim, CA",CA,798333.0,802667.0,818000.0,835000.0,848300.0,849633.0,841300.0,...,1005698.0,1006364.0,1006666.0,999666.0,991333.0,971333.0,946667.0,931633.0,33.782237,-118.151925
394463,3,"Chicago, IL",IL,301000.0,305967.0,319300.0,335967.0,345967.0,347967.0,343300.0,...,338300.0,346633.0,352967.0,354667.0,354633.0,348267.0,339933.0,332967.0,41.875562,-87.624421
394514,4,"Dallas-Fort Worth, TX",TX,341996.0,345330.0,351663.0,359830.0,366163.0,366067.0,359533.0,...,357025.0,365358.0,374884.0,383333.0,390167.0,393500.0,396500.0,397667.0,32.896519,-97.046522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394528,90,"Daytona Beach, FL",FL,269600.0,270300.0,271833.0,274833.0,279667.0,284500.0,287833.0,...,303500.0,314467.0,324467.0,336078.0,341612.0,346278.0,348000.0,352967.0,29.210815,-81.022833
394531,91,"Des Moines, IA",IA,281600.0,285967.0,292293.0,297293.0,299593.0,299900.0,299900.0,...,283300.0,291378.0,301725.0,311707.0,319628.0,320032.0,317550.0,314217.0,41.591032,-93.604665
395006,100,"Provo, UT",UT,389707.0,397680.0,408503.0,413706.0,409865.0,402848.0,399210.0,...,510630.0,512444.0,520778.0,537478.0,546633.0,549967.0,548467.0,545533.0,40.233844,-111.658534
394549,104,"Durham, NC",NC,362699.0,367241.0,375112.0,382984.0,386785.0,384029.0,379488.0,...,442273.0,466005.0,485372.0,495967.0,487633.0,480160.0,476526.0,478160.0,35.996653,-78.901805
394602,159,"Fort Collins, CO",CO,442736.0,445785.0,448272.0,450000.0,454094.0,458112.0,456446.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.550853,-105.066808

#### Top 10 expensive cities per month: Expensive_df

In [11]:
Expensive_df = pd.DataFrame()
for date in datelist:
    df_t = df.nlargest(10,date)
    Expensive_df[date] = df_t['RegionName'].tolist()
Expensive_df

,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,...,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31
0,"San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA",...,"San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA","San Jose, CA"
1,"San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA",...,"Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA"
2,"Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA",...,"San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA","San Francisco, CA"
3,"Ventura, CA","Ventura, CA","Ventura, CA","Ventura, CA","Stamford, CT","Stamford, CT","Stamford, CT","Stamford, CT","Stamford, CT","Stamford, CT",...,"San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA"
4,"San Diego, CA","San Diego, CA","Stamford, CT","Stamford, CT","Ventura, CA","Ventura, CA","Ventura, CA","Ventura, CA","Ventura, CA","Ventura, CA",...,"Stamford, CT","Stamford, CT","Stamford, CT","Stamford, CT","Stamford, CT","Stamford, CT","Stamford, CT","Stamford, CT","Stamford, CT","Seattle, WA"
5,"Stamford, CT","Stamford, CT","San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA","San Diego, CA",...,"Boston, MA","Boston, MA","Boston, MA","Boston, MA","Seattle, WA","Seattle, WA","Seattle, WA","Seattle, WA","Seattle, WA","Stamford, CT"
6,"Urban Honolulu, HI","Urban Honolulu, HI","Urban Honolulu, HI","Urban Honolulu, HI","Urban Honolulu, HI","Urban Honolulu, HI","Urban Honolulu, HI","Urban Honolulu, HI","Urban Honolulu, HI","Urban Honolulu, HI",...,"New York, NY","New York, NY","New York, NY","Seattle, WA","Boston, MA","Boston, MA","Boston, MA","Boston, MA","Boston, MA","Boston, MA"
7,"Boston, MA","Boston, MA","Boston, MA","Seattle, WA","Seattle, WA","Seattle, WA","Seattle, WA","Seattle, WA","Seattle, WA","Seattle, WA",...,"Seattle, WA","Seattle, WA","Seattle, WA","New York, NY","New York, NY","New York, NY","New York, NY","New York, NY","New York, NY","New York, NY"
8,"New York, NY","Seattle, WA","Seattle, WA","Boston, MA","Boston, MA","Boston, MA","Boston, MA","Boston, MA","New York, NY","New York, NY",...,"Sacramento, CA","Sacramento, CA","Sacramento, CA","Sacramento, CA","Sacramento, CA","Sacramento, CA","Sacramento, CA","Sacramento, CA","Denver, CO","Denver, CO"
9,"Seattle, WA","New York, NY","New York, NY","New York, NY","New York, NY","New York, NY","New York, NY","New York, NY","Boston, MA","Boston, MA",...,"Denver, CO","Denver, CO","Denver, CO","Denver, CO","Denver, CO","Denver, CO","Denver, CO","Denver, CO","Sacramento, CA","Sacramento, CA"

#### Percentage of Total Median Sales: PercentPerState_df   &   PercentPerCity_df

*What percentage does the state make up of the entire country for median sales price?*

In [12]:
PercentPerState_df = pd.DataFrame(columns=['StateName'] + datelist)
PercentPerState_df['StateName'] = statelist

for date in datelist:
    percentPerDate = []
    for state in statelist:
        stateSum = df_noNaN.loc[df['StateName']==state][date].sum()
        totalSum = df_noNaN[date].sum()
        percentPerDate.append(stateSum/totalSum) #sum of the states medians
    PercentPerState_df[date] = percentPerDate

# for state in statelist:
#     percentPerDate = []
#     percentPerDatePerRegion = []
#     for date in datelist:
#         #PER STATE
#         stateSum = df_noNaN.loc[df['StateName']==state][date].sum()
#         totalSum = df[date].sum()
#         percentPerDate.append(stateSum/totalSum) #sum of the states medians
#     PercentPerState_df[state] = percentPerDate

PercentPerState_df

,StateName,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,...,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31
0,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,NY,0.041287,0.041434,0.041696,0.041851,0.042029,0.042180,0.042417,0.042677,0.042234,...,0.042018,0.042366,0.042633,0.042516,0.041845,0.040868,0.040111,0.039230,0.038610,0.037996
2,CA,0.196852,0.197323,0.197121,0.197184,0.196304,0.195810,0.194367,0.192276,0.187191,...,0.198726,0.196191,0.194158,0.192012,0.190359,0.190299,0.190549,0.190731,0.190450,0.190307
3,IL,0.009948,0.009998,0.010210,0.010474,0.010589,0.010561,0.010455,0.010375,0.010165,...,0.010566,0.010397,0.010414,0.010405,0.010383,0.010303,0.010296,0.010201,0.010050,0.009895
4,TX,0.055226,0.054800,0.054174,0.053602,0.053226,0.053026,0.052862,0.052871,0.052163,...,0.051655,0.058308,0.058512,0.058711,0.059133,0.059870,0.061166,0.062551,0.063588,0.064099
5,PA,0.021386,0.020991,0.020873,0.020894,0.021126,0.021273,0.021487,0.021598,0.021333,...,0.026993,0.026858,0.026863,0.026753,0.026560,0.026304,0.025982,0.025715,0.025688,0.025723
6,DC,0.014261,0.014089,0.014117,0.014112,0.014221,0.014407,0.014608,0.014686,0.014383,...,0.016455,0.016071,0.015729,0.015499,0.015379,0.015343,0.015286,0.015280,0.015314,0.015385
7,FL,0.078071,0.077497,0.076422,0.075286,0.074586,0.074374,0.074712,0.075302,0.074603,...,0.060310,0.059459,0.059147,0.059349,0.060328,0.061697,0.063217,0.064935,0.066441,0.067839
8,GA,0.010248,0.010292,0.010348,0.010454,0.010549,0.010612,0.010504,0.010419,0.010159,...,0.011159,0.011022,0.011060,0.011277,0.011492,0.011668,0.011739,0.011843,0.011895,0.011887
9,MA,0.035057,0.034842,0.035079,0.035403,0.035765,0.035758,0.035439,0.035024,0.034240,...,0.030839,0.030535,0.030770,0.030916,0.030736,0.030489,0.030123,0.029707,0.029444,0.029163
10,MI,0.015916,0.015954,0.016194,0.016527,0.016888,0.017096,0.017143,0.017057,0.016649,...,0.018616,0.018565,0.018718,0.018846,0.018938,0.019021,0.018984,0.018783,0.018378,0.017970
11,AZ,0.019837,0.019918,0.019918,0.019761,0.019641,0.019470,0.019433,0.019504,0.019454,...,0.023481,0.023371,0.023537,0.023705,0.023965,0.024246,0.024532,0.024847,0.025029,0.025111
12,WA,0.016800,0.017264,0.017906,0.018237,0.018312,0.018199,0.018048,0.017913,0.017505,...,0.020462,0.020481,0.020521,0.020512,0.020443,0.020382,0.020371,0.020356,0.020448,0.020456
13,MN,0.011715,0.012147,0.012385,0.012251,0.011974,0.011635,0.011410,0.011328,0.011089,...,0.011826,0.011879,0.011911,0.011764,0.011529,0.011260,0.011149,0.011071,0.011017,0.010936
14,MO,0.014736,0.014745,0.014907,0.014951,0.015016,0.015002,0.015069,0.015164,0.015169,...,0.018580,0.018698,0.019078,0.019305,0.019099,0.018657,0.018072,0.017656,0.017396,0.017287
15,MD,0.010022,0.009800,0.009750,0.009767,0.009997,0.010258,0.010536,0.010666,0.010524,...,0.010659,0.010478,0.010460,0.010405,0.010448,0.010414,0.010504,0.010445,0.010424,0.010183
16,CO,0.030368,0.030066,0.029356,0.028563,0.028111,0.027615,0.027174,0.026873,0.041627,...,0.016971,0.017075,0.017177,0.017301,0.017453,0.017669,0.017901,0.018119,0.018280,0.018425
17,OR,0.015196,0.015234,0.015112,0.014933,0.014709,0.014586,0.014538,0.014519,0.014268,...,0.016606,0.016437,0.016417,0.016509,0.016854,0.017080,0.017207,0.017174,0.017137,0.017028
18,NC,0.048392,0.048187,0.048098,0.048137,0.048181,0.048052,0.048411,0.049021,0.049017,...,0.055574,0.054875,0.054736,0.054854,0.055041,0.054955,0.054758,0.054930,0.055402,0.055789
19,OH,0.034209,0.034186,0.034744,0.035700,0.036536,0.037233,0.037677,0.037675,0.036783,...,0.043025,0.043090,0.043712,0.044181,0.044302,0.043929,0.043489,0.042764,0.041812,0.040517
20,NV,0.009590,0.009541,0.009432,0.009549,0.009932,0.010365,0.010643,0.010728,0.010519,...,0.011023,0.010815,0.010877,0.011137,0.011649,0.012084,0.012388,0.012741,0.013107,0.013542
21,IN,0.006929,0.007013,0.007246,0.007844,0.008335,0.008620,0.008497,0.008313,0.008002,...,0.008778,0.008713,0.008771,0.008803,0.008763,0.008684,0.008582,0.008620,0.008622,0.008658
22,VA,0.018356,0.018166,0.018111,0.018162,0.018238,0.018297,0.018440,0.018601,0.018437,...,0.021913,0.021603,0.021342,0.020933,0.020518,0.020078,0.019723,0.019586,0.019636,0.019697
23,TN,0.027492,0.027040,0.026583,0.026395,0.026315,0.026417,0.026504,0.026599,0.026323,...,0.029723,0.029351,0.029395,0.029874,0.030498,0.030911,0.030983,0.031098,0.031405,0.031620
24,RI,0.011431,0.011359,0.011288,0.011220,0.011177,0.011135,0.011178,0.011317,0.011313,...,0.012648,0.012764,0.012559,0.012358,0.012100,0.012335,0.012666,0.012934,0.012956,0.012974
25,WI,0.016839,0.016932,0.017103,0.017252,0.017367,0.017474,0.017589,0.017620,0.017295,...,0.018419,0.018211,0.018025,0.017773,0.017759,0.017646,0.017540,0.017305,0.017193,0.017135
26,OK,0.014201,0.014123,0.014113,0.014107,0.014101,0.014014,0.014032,0.014102,0.014043,...,0.018065,0.017854,0.018214,0.018500,0.018585,0.017966,0.017414,0.017129,0.017172,0.017137
27,KY,0.007673,0.007858,0.008125,0.008310,0.008405,0.008396,0.008370,0.008371,0.008255,...,0.008025,0.008066,0.008213,0.008259,0.008309,0.008268,0.008216,0.008152,0.008021,0.007914
28,CT,0.040605,0.041657,0.042702,0.042893,0.042682,0.042389,0.042167,0.042010,0.041390,...,0.044339,0.044837,0.045429,0.045509,0.044752,0.043816,0.042694,0.041258,0.040206,0.039841
29,LA,0.015757,0.015504,0.015289,0.015260,0.015371,0.015506,0.015609,0.015706,0.015572,...,0.018090,0.017793,0.017636,0.017717,0.017902,0.018104,0.018174,0.018227,0.018290,0.018395
30,AL,0.006831,0.006771,0.006882,0.007071,0.007231,0.007272,0.007306,0.007396,0.007343,...,0.008758,0.008683,0.008566,0.008503,0.008432,0.008376,0.008274,0.008298,0.008367,0.008592
31,UT,0.038001,0.038286,0.038491,0.038293,0.037911,0.037602,0.037682,0.037938,0.037564,...,0.016307,0.016147,0.015719,0.015383,0.015319,0.015613,0.015871,0.016109,0.016215,0.016213
32,HI,0.021923,0.021621,0.020944,0.020212,0.019935,0.019976,0.020196,0.020611,0.020701,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
33,NM,0.007893,0.007857,0.007835,0.007843,0.007890,0.007923,0.007899,0.007856,0.007683,...,0.010776,0.010645,0.010680,0.010615,0.010683,0.010657,0.010747,0.010837,0.010987,0.011310
34,NE,0.009204,0.009358,0.009425,0.009506,0.009494,0.009416,0.009345,0.009357,0.009270,...,0.010228,0.010279,0.010338,0.010304,0.010099,0.009730,0.009387,0.009226,0.009209,0.009302
35,SC,0.027255,0.027100,0.026959,0.026928,0.026957,0.027122,0.027272,0.027435,0.026993,...,0.030203,0.030104,0.030303,0.030735,0.031168,0.031733,0.032030,0.032206,0.032095,0.032025
36,AR,0.005590,0.005607,0.005540,0.005477,0.005444,0.005445,0.005455,0.005475,0.005425,...,0.006821,0.006722,0.006808,0.006798,0.006808,0.006736,0.006773,0.006832,0.006843,0.006829
37,KS,0.005837,0.005972,0.006110,0.006269,0.006322,0.006321,0.006287,0.006262,0.006188,...,0.007275,0.007359,0.007483,0.007434,0.007129,0.006748,0.006473,0.006296,0.006208,0.006290
38,ID,0.010783,0.011206,0.011136,0.011056,0.010915,0.010976,0.010971,0.010944,0.010837,...,0.014724,0.014725,0.014889,0.015177,0.015569,0.016017,0.016271,0.016307,0.016141,0.016048
39,IA,0.009307,0.009344,0.009346,0.009268,0.009169,0.009102,0.009133,0.009174,0.009068,...,0.008726,0.008708,0.008721,0.008747,0.008876,0.009055,0.009280,0.009374,0.009388,0.009338

*What percentage does the city make up of the state it is in for median sales price?*

In [13]:
PercentPerCity_df = pd.DataFrame(columns=['RegionName','StateName'] + datelist)
PercentPerCity_df['RegionName'] = df_noNaN.loc[df_noNaN['StateName']==ReportState]['RegionName'].tolist()
PercentPerCity_df['StateName'] = df_noNaN.loc[df_noNaN['StateName']==ReportState]['StateName'].tolist()

regionsInState = df_noNaN.loc[df_noNaN['StateName']==ReportState]['RegionName'].tolist()

for date in datelist:
    percentPerDate = []
    for region in regionsInState:
        regionAmount = df_noNaN.loc[df['RegionName']==region][date].sum()
        stateSum = df_noNaN.loc[df['StateName']==ReportState][date].sum()
        percentPerDate.append(regionAmount/stateSum) #sum of the states medians
    PercentPerCity_df[date] = percentPerDate

PercentPerCity_df

,RegionName,StateName,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,...,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31
0,"Charlotte, NC",NC,0.230820,0.229203,0.228027,0.226460,0.226334,0.226652,0.223831,0.220031,...,0.215188,0.215323,0.215715,0.216293,0.218220,0.219606,0.220276,0.218137,0.216286,0.216798
1,"Raleigh, NC",NC,0.244457,0.243873,0.243738,0.243926,0.243465,0.242084,0.239840,0.237653,...,0.227238,0.228693,0.228361,0.227136,0.225549,0.224809,0.226878,0.230262,0.232214,0.231680
2,"Greensboro, NC",NC,0.133634,0.134380,0.137037,0.141273,0.145850,0.148413,0.151792,0.155955,...,0.150534,0.149289,0.148733,0.146535,0.144529,0.142789,0.144109,0.145375,0.144240,0.138663
3,"Winston-Salem, NC",NC,0.143377,0.143512,0.141824,0.140302,0.138651,0.140286,0.145816,0.152936,...,0.161674,0.160012,0.158462,0.155017,0.152298,0.150632,0.150190,0.150192,0.152974,0.158142
4,"Durham, NC",NC,0.247712,0.249032,0.249375,0.248039,0.245700,0.242565,0.238721,0.233426,...,0.245367,0.246683,0.248729,0.255020,0.259403,0.262165,0.258547,0.256034,0.254288,0.254717

## Load

### Heatmap View

In [25]:
heatmap = px.density_mapbox(LatLon_df, lat='Latitude', lon='Longitude', z=ReportDate, hover_name='RegionName',
                        radius=50, center=dict(lat=37.0902, lon=-98), zoom=2.5,
                        mapbox_style="stamen-terrain")
plot(heatmap,filename=ReportPath + '/figures/heatmap.html')
heatmap.write_image(ReportPath + "/figures/heatmap.png")

### LineChart Time View

In [16]:
linechart = px.line(df_StateByDate, x='Dates', y=ReportRegion, labels={'x': 'Date', 'y': 'Price'})
plot(linechart,filename=ReportPath + '/figures/linechart.html')
linechart.write_image(ReportPath + "/figures/linechart.png")

### PieChart View

#### State / Country

In [17]:
piechart = px.pie(PercentPerState_df, values=ReportDate, names='StateName')
plot(piechart,filename=ReportPath + '/figures/piechart.html')
piechart.write_image(ReportPath + "/figures/piechart.png")

#### City / State

In [18]:
piechart2 = px.pie(PercentPerCity_df, values=ReportDate, names='RegionName')
plot(piechart2,filename=ReportPath + '/figures/piechart2.html')
piechart2.write_image(ReportPath + "/figures/piechart2.png")

### BoxPlot View

In [19]:
boxplot = px.box(df_StateByDate, y=ReportRegion)
plot(boxplot,filename=ReportPath + '/figures/boxplot.html')
boxplot.write_image(ReportPath + "/figures/boxplot.png")

### Generate Report

In [20]:
from IPython.display import display, HTML
graphs = [
    [ReportPath + '/figures/heatmap.html', ReportPath + '/figures/heatmap.png'],
    [ReportPath + '/figures/linechart.html', ReportPath + '/figures/linechart.png'],
    [ReportPath + '/figures/piechart.html', ReportPath + '/figures/piechart.png'],
    [ReportPath + '/figures/piechart2.html', ReportPath + '/figures/piechart2.png'],
    [ReportPath + '/figures/boxplot.html', ReportPath + '/figures/boxplot.png'],
]
    # 'https://plotly.com/~christopherp/308',
    # 'https://plotly.com/~christopherp/306',
    # 'https://plotly.com/~christopherp/300',
    # 'https://plotly.com/~christopherp/296'


def report_block_template(report_type, graph_url, caption=''):
    graph_block = '<H3>' + '{caption}' + '</H3>'

    if report_type == 'interactive':
        graph_block += '<iframe style="border: none;" src="{graph_url[1]}" width="100%" height="600px"></iframe>'
    elif report_type == 'static':
        graph_block += (''
            '<a href="{graph_url[1]}" target="_blank">' # Open the interactive graph when you click on the image
                '<img style="height: 400px;" src="{graph_url[1]}">'
            '</a>')

    report_block = ('' +
        graph_block +
        '<br>'      + # Line break
        '<a href="{graph_url[0]}" style="color: rgb(190,190,190); text-decoration: none; font-weight: 200;" target="_blank">'+
            'Click to comment and see the interactive graph' + # Direct readers to Plotly for commenting, interactive graph
        '</a>' +
        '<br>' +
        '<hr>') # horizontal line                       

    return report_block.format(graph_url=graph_url, caption=caption)


interactive_report = '<H1> Zillow Housing Sales Report for ' + ReportDate + '</H1><H2>' + ReportRegion + '</H2></br>'
static_report = ''

#ADD CHARTS HERE
interactive_report += report_block_template('interactive', graphs[0], caption='HeatMap of Median listed Sales Price in the USA on ' + ReportDate)
interactive_report += report_block_template('interactive', graphs[1], caption='Median listed sales price per month in ' + ReportRegion)
interactive_report += report_block_template('interactive', graphs[2], caption='Percentage per State of median sales price to total of all states on ' + ReportDate)
interactive_report += report_block_template('interactive', graphs[3], caption='Percentage per City of median sales price to total of the state on ' + ReportDate)
interactive_report += report_block_template('interactive', graphs[4], caption='Boxplot of house listing prices in ' + ReportRegion)

with open('report.html', 'w', encoding = 'utf8') as f:
    f.write(interactive_report)

testing

In [ ]:
df_stocks = px.data.stocks()
#px.line(df_stocks, x='date', y='GOOG', labels={'x': 'Date', 'y': 'Price'})
df_stocks.head()

In [ ]:
px.line(df_StateByDate, x='Dates', y='New York, NY', labels={'x': 'Date', 'y': 'Price'})

In [ ]:
fig = px.density_mapbox(LatLon_df, lat='Latitude', lon='Longitude', z='2018-01-31', radius=70,
                        center=dict(lat=37.0902, lon=-70), zoom=3,
                        mapbox_style="stamen-terrain")
fig.show()

In [ ]:
fig = px.pie(PercentPerCity_df, values=ReportDate, names='RegionName')
fig.show()

In [ ]:
df_StateByDate
fig = px.box(df_StateByDate, y=ReportRegion)
fig.show()